# Keep compilation settings in this file and user/runtime settings in `esp-config.toml`.
include = ["esp-config.toml", "secrets.toml"]

[target.xtensa-esp32s3-none-elf]
runner = "probe-rs run --chip=esp32s3 --preverify --always-print-stacktrace --no-location"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]

# .cargo/config.toml
[env]
DEFMT_LOG = "info"
